#! /bin/sh
test "${ZSH_VERSION+set}" = set && alias -g '${1+"$@"}'='"$@"'
cd '/home/centos/gnucobol-3.0-rc1/tests'
exec ${CONFIG_SHELL-/bin/sh} "/home/centos/gnucobol-3.0-rc1/tests/./testsuite" -v -d  268 ${1+"$@"}
exit 1
